$ANSIBLE_VAULT;1.1;AES256
61363762303363346261653263306438383936636566346264333634373635363463383532343734
3662363464623565336433316266613463306135366435350a303866656362356166616263323566
63613364666336636439656135636464376435353638623866613034386530363263663639333563
6537303137653530660a653663333237623039396133376564646663663232393331626635393438
38303166303661336336626165343265636535663333316434353636373764363264646464666466
64343137306262306361363132376662343035306130656533393831613139656539396231646637
66666265623235373761313765353839636332316239366465393861613831386435656335383430
32353062323436306239333437393262346136363839303139336535353462383966623732316235
66303964666465326335636137636464316331393932626233353936663238313130363665313662
39656330393934316134386266653537316535306430396464366333356530636166636539396639
65626463356136613733373965346538636237653939633037346336623432613937343861363863
66646164313933613136323531383630656337643061623033373537616561303933386165366431
32333138363336336164666361353134353930343330633036326534646434326332396465383464
63396334346264393833313334666363376430336430636537613764613164326336623365613236
65633432383534356565333633616533353735323135653161633465363031643030663064353738
34343061343963346261623138656132356639353766353931623835383163613263303664353132
35353863333633626132336662653631326439663261366161326161633935316666366339633164
3166333432313762393266326664363363383263396337613435
