---
- name: Update system and install roles
  hosts: webservers
  become: true

  vars:
    pip_install_packages:
      - name: docker
    pg_env_file_path: "/tmp/postgres.env"
    rm_env_file_path: "/tmp/redmine.env"
    datadog_api_key: "{{ datadog_vars.datadog_api_key }}"
    datadog_site: "{{ datadog_vars.datadog_site }}"

  pre_tasks:
    - name: Perform full system upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

  tasks:
    - name: 1. Create Docker network
      community.docker.docker_network:
        name: redmine_network
        state: present

    - name: 2. Generate PostgreSQL .env file
      ansible.builtin.template:
        src: ./templates/postgres.env.j2
        dest: "{{ pg_env_file_path }}"
        mode: '0644'

    - name: 3. Generate Redmine .env file
      ansible.builtin.template:
        src: ./templates/redmine.env.j2
        dest: "{{ rm_env_file_path }}"
        mode: '0644'

    - name: 4. Start Redmine container
      community.docker.docker_container:
        name: redmine_container
        image: redmine:latest
        state: started
        env_file: "{{ rm_env_file_path }}"
        ports:
          - "{{ redmine_port }}:{{ redmine_port }}"
        networks:
          - name: redmine_network

    - name: 5. Remove .env files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ pg_env_file_path }}"
        - "{{ rm_env_file_path }}"

    - name: Import the Datadog Agent role from the Datadog collection
      import_role:
        name: datadog.dd.agent

  roles:
    - geerlingguy.pip
    - geerlingguy.docker